// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW65XH7wFxaTsCbpoLu3SbMCTKe4BezvM',
    appId: '1:1092441861337:android:92a18743100daa1f12e2c8',
    messagingSenderId: '1092441861337',
    projectId: 'instagram-clone-6d5c6',
    databaseURL: 'https://instagram-clone-6d5c6-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-clone-6d5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYOwdppjgGQ2UiGpCAIt7lKbEua5fmsXw',
    appId: '1:1092441861337:ios:8ac3e82600374ddf12e2c8',
    messagingSenderId: '1092441861337',
    projectId: 'instagram-clone-6d5c6',
    databaseURL: 'https://instagram-clone-6d5c6-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-clone-6d5c6.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
